[tool.isort]
profile = "black"
src_paths = [ "src" ]

[tool.pytest.ini_options]
python_files = ["tests.py", "test_*.py", "*_tests.py"]
testpaths = [
    "src",
    "tests",
]

[tool.coverage.report]
exclude_lines = [
    'if __name__ == "__main__":'
]
